### ISSUE TITLE
Unable to connect via proxy...

### ISSUE THREAD

**Issue by tracker1** [rickparrish/fTelnetProxy#1]
I've got my proxy setup on `ftelnet-proxy.roughneckbbs.com` and using the following with ftelnet config...

```
fTelnet.ProxyHostname = "ftelnet-proxy.roughneckbbs.com";
fTelnet.ProxyPort = 80;
fTelnet.ProxyPortSecure = 443;  
```

I'm receiving the following error message: 

```
Sorry, for security reasons this proxy won't connect to localhost:23
```

The proxy itself is setup running on dokku, with the letsencrypt plugin... My changes and the [dockerfile is with my changes](https://github.com/tracker1/fTelnetProxy/blob/master/Dockerfile).

The issue seems to be related to a missing `RelayFilename`, and your repo is missing the `fTelnetProxy.ini` file that was referenced in the project, so I don't have an example to work from here.

**Comment by rickparrish** [comment]
How are you planning to setup fTelnetProxy:
- All connections to ftelnet-proxy.roughneckbbs.com get connected to one telnet server that you specify
- Each client connection will be able to specify which telnet server they want to be connected to

**Comment by tracker1** [comment]
I'd like to be able to support rlogin and telnet proxies, and all connections go to shell.roughneckbbs.com (telnet or rlogin respectively) ... I changed back to one of the public proxies... was just concerned with passing the rlogin username/password for users through the public proxy.

I kind of figured out "something" for the configuration files, but not sure if they are correct in my fork, or what they should be for that matter.  a settings file for the project isn't in github.

**Comment by rickparrish** [comment]
Hmm, I hadn't given much thought to the fact that there's a need for both telnet and rlogin redirection.  I just committed a change that allows an rlogin port to be specified (which will default to 513).

So when you start fTelnetProxy you'll want to use "-t shell.roughneckbbs.com:23" to tell fTelnetProxy where to redirect users to.  If your rlogin port is on 513 then that should be all you need, but if by chance you're running rlogin on a non-standard port then also use "-rp <rlogin_port>" to specify the rlogin port.

And after fTelnetProxy is launched for the first time it should save a default fTelnetProxy.ini, which can be customized, or you can continue passing settings on the command-line (they override whatever is found in the .ini file).

**Comment by tracker1** [comment]
Would it be possible to check environment variables?

```
FTELNET_TARGET - the hostname to proxy requests to
FTELNET_TP - the telnet port for the target
FTELNET_RP - the rlogin port for the target
PORT - the HTTP port to bind to for websocket connections
```

This way a generic Dockerfile can be added in this project, and deployments can set their own configuration with environment variables on the docker process, without having to change the structure at all... it can also then be published to dockerhub, and pulled from there.

Just a couple suggestions... thanks for the help.  The telnet port, rlogin port could be default and the listen port could be whatever it's existing default is...

**Comment by rickparrish** [comment]
Sure, just pushed an update that checks environment variables as well.  Anything that can be passed on the command-line can now be passed via environment variable using the same name and an FTELNET_ prefix (so for example both FTELNET_RP and FTELNET_RLOGIN_PORT are valid for setting the rlogin port).

**Comment by tracker1** [comment]
Will test out the latest with a generic dockerfile tonight, will then do a PR for the small dockerfile, in case you care to add it, and push it to dockerhub.
