### ISSUE TITLE
No instructions for linux

### ISSUE THREAD

**Issue by kcasteels** [rickparrish/fTelnetProxy#2]
I'd like to install fTelnetProxy on a Debian based system (Raspberry Pi) but there are no instructions on how to do so.  I've successfully compiled mono from source, but am not sure how to move forward with the rest.  Thanks!

**Comment by rickparrish** [comment]
There are compiled binaries in the bin/Release directory, so if you have mono up and running it should just be a matter of running mono fTelnetProxy.exe
