### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by k5jat** [rickparrish/fTelnetProxy#3]
This project is missing libraries to be compilable. I tried compiling it using the latest Mono git and this was the output:

`XBuild Engine Version 14.0
Mono, Version 4.9.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 2/5/2017 6:47:57 AM.
__________________________________________________
/root/ftelnetproxy/fTelnetProxy.sln:  warning : Project file /root/DLL/RMLib/RMLib.csproj referenced in the solution file, not found. Ignoring.
Project "/root/ftelnetproxy/fTelnetProxy.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Debug|Mixed Platforms".
        Target Build:
/root/ftelnetproxy/fTelnetProxy.sln: error : Could not find the project file '/root/DLL/RMLib/RMLib.csproj'
                Project "/root/ftelnetproxy/fTelnetProxy.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug Platform: x86
                                Created directory "bin/Debug/"
                                Created directory "obj/x86/Debug/"
                        Target ResolveProjectReferences:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Referenced Project ../DLL/RMLib/RMLib.csproj not found, ignoring.
                        Target GenerateResources:
                                Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "ProjectInstaller.resx,obj/x86/Debug/fTelnetProxy.ProjectInstaller.resources"
                                Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "Service.resx,obj/x86/Debug/RandM.fTelnetProxy.Service.resources"
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool /usr/lib/mono/4.5/csc.exe execution started with arguments: /noconfig /debug:full /debug:portable /optimize- /out:obj/x86/Debug/fTelnetProxy.exe /resource:obj/x86/Debug/fTelnetProxy.ProjectInstaller.resources /resource:obj/x86/Debug/RandM.fTelnetProxy.Service.resources Config.cs fTelnetProxy.cs ProjectInstaller.cs ProjectInstaller.Designer.cs WebSocketClientThread.cs WebSocketServerThread.cs Service.cs Service.Designer.cs Program.cs Properties/AssemblyInfo.cs /target:exe /define:"DEBUG;TRACE" /nostdlib /platform:x86 /reference:/usr/lib/mono/2.0-api/System.dll /reference:/usr/lib/mono/2.0-api/System.Configuration.Install.dll /reference:/usr/lib/mono/2.0-api/System.Data.dll /reference:/usr/lib/mono/2.0-api/System.Data.Linq.dll /reference:/usr/lib/mono/2.0-api/System.Management.dll /reference:/usr/lib/mono/2.0-api/System.ServiceProcess.dll /reference:/usr/lib/mono/2.0-api/System.Xml.dll /reference:/usr/lib/mono/2.0-api/System.Core.dll /reference:/usr/lib/mono/2.0-api//mscorlib.dll /warn:4
                                Microsoft (R) Visual C# Compiler version 2.0.0.61324
                                Copyright (C) Microsoft Corporation. All rights reserved.
Config.cs(1,13): error CS0234: The type or namespace name 'RMLib' does not exist in the namespace 'RandM' (are you missing an assembly reference?)
fTelnetProxy.cs(1,13): error CS0234: The type or namespace name 'RMLib' does not exist in the namespace 'RandM' (are you missing an assembly reference?)
WebSocketClientThread.cs(1,13): error CS0234: The type or namespace name 'RMLib' does not exist in the namespace 'RandM' (are you missing an assembly reference?)
WebSocketServerThread.cs(1,13): error CS0234: The type or namespace name 'RMLib' does not exist in the namespace 'RandM' (are you missing an assembly reference?)
Program.cs(1,13): error CS0234: The type or namespace name 'RMLib' does not exist in the namespace 'RandM' (are you missing an assembly reference?)
Config.cs(7,27): error CS0246: The type or namespace name 'ConfigHelper' could not be found (are you missing a using directive or an assembly reference?)
Config.cs(11,16): error CS0246: The type or namespace name 'LogLevel' could not be found (are you missing a using directive or an assembly reference?)
Config.cs(34,25): warning CS0109: The member 'Config.Load()' does not hide an accessible member. The new keyword is not required.
fTelnetProxy.cs(276,43): error CS0246: The type or namespace name 'RMLogEventArgs' could not be found (are you missing a using directive or an assembly reference?)
WebSocketClientThread.cs(10,42): error CS0246: The type or namespace name 'RMThread' could not be found (are you missing a using directive or an assembly reference?)
WebSocketClientThread.cs(19,33): error CS0115: 'WebSocketClientThread.Dispose(bool)': no suitable method found to override
WebSocketClientThread.cs(33,33): error CS0115: 'WebSocketClientThread.Execute()': no suitable method found to override
WebSocketServerThread.cs(10,42): error CS0246: The type or namespace name 'RMThread' could not be found (are you missing a using directive or an assembly reference?)
WebSocketServerThread.cs(46,33): error CS0115: 'WebSocketServerThread.Execute()': no suitable method found to override
WebSocketServerThread.cs(92,30): error CS0115: 'WebSocketServerThread.Stop()': no suitable method found to override
WebSocketServerThread.cs(16,17): error CS0246: The type or namespace name 'WebSocketConnection' could not be found (are you missing a using directive or an assembly reference?)
`

**Comment by k5jat** [comment]
Ok, I found the missing libraries at https://github.com/rickparrish/RMLib

Linux installation is a PITA... Still working it out.... Maybe I'll write something up.

**Comment by rickparrish** [comment]
Glad you found the missing library.  It is a bit of a pain to compile, but there's binaries in the bin/Release directory so you don't necessarily have to compile on your own.

**Comment by houseofadawg** [comment]
I'm working on getting this up and running after installing SSL on my webserver.  Everything was great up to the point of forcing an SSL connection.

Anyway, I was wondering if you wouldn't mind sharing the configuration changes that were necessary to implement wss:// on your webserver.

Thanks in advance.
