### ISSUE TITLE
Relaying

### ISSUE THREAD

**Issue by dragon-github** [rickparrish/fTelnetProxy#4]
Sorry to bother you, but I am hosting my own Proxy on a closed LAN, and I really would like to be able to use the relay function with a dynamic web page.

I've added a relay.cfg but cannot get the webpage to load when I have Options.TargetHostname and Options.TargetPort defined in my script.
my relay.cfg is simply:

23,24
10.0.0.22:24

but when I add:

Options.TargetHostname = 10.0.0.22;
Options.TargetPort = 24;

to my script, the page fails to load.

Do you have time to help?

**Comment by 3FLLC** [comment]
I will give you a hand, as I run Rick's code, and have written my own fTelnetProxy clone... so I am very familiar with what it can and cannot do. When you state "cannot get the webpage" to load, are you hitting 10.0.0.22:24 in your browser as http://10.0.0.22:24/ or, are you trying to get fTelnetProxy to point to an HTTP server or TELNET server? Your description of the topology is a little vague...

(you can also reach me @ ozznixon (at) gmail (dot) com)

**Comment by tracker1** [comment]
@3FLLC a bit offtopic, but what did you write your proxy clone in?  Wanting to integrate it into a node web service if you have a good example... Haven't had time to dig into it just yet though... it's on my todo list.

**Comment by rickparrish** [comment]
Sorry for not seeing this sooner.  I'm going to close the issue, but if by chance you still need help after all this time feel free to re-open it.
