### ISSUE TITLE
Program crashes upon start (Linux)

### ISSUE THREAD

**Issue by phiwer** [rickparrish/fTelnetProxy#5]
I am trying to compile and run this on Linux, but the program crashes when trying to run it:

`
mono ./fTelnetProxy.exe "/?"
[3/17/2022 9:34:31 PM] [Info] fTelnetProxy Starting Up
[3/17/2022 9:34:31 PM] [Info] fTelnetProxy shutting down
[3/17/2022 9:34:31 PM] [Info] fTelnetProxy terminated
[3/17/2022 9:34:31 PM] [Error] Message: Unhandled exception in main program loop
File: :0,0
Method: RandM.RMLib.ConfigHelper::Save
Exception: Object reference not set to an instance of an object
`

The README states that the config (ini) file should be created first time during startup, but that does not seem to happen. Am I doing something wrong?

The RMLib project is also not a part of the project, but I used the binary release and added that to the project.

**Comment by rickparrish** [comment]
Thanks for the heads up, looks like I broke things when I added the new User property to the config file and set the default to null instead of a blank string.  Just pushed a new commit that should take care of that.

**Comment by phiwer** [comment]
Thanks for the quick fix.

One more suggestion. The project depends on RMLib, which I didn't understand was another project of yours. Please add this to the README, as it's confusing when you load the project, and you don't understand where to find it.

Secondly, I would probably add a pre-built RMLib DLL to this project (and add that reference to the project file), or create a nuget packet of RMLib and pull it through there. :)

**Comment by phiwer** [comment]
Final comment. :)

The build configuration that is pushed here does not actually build fTelnetProxy by default. You probably want to change that as well.

Thanks.

**Comment by rickparrish** [comment]
Thanks for the suggestions.  I've updated the README and fixed the build errors related to files I wasn't committing to the repo.
